# Generated by Django 5.0.1 on 2024-01-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sca",
            fields=[
                ("id", models.BigAutoField(auto_created=True,serialize=False,verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=11,primary_key=True)),
                ("matricula", models.CharField(max_length=12)),
                ("disciplinas", models.IntegerField(max_length=2)),
                ("curso", models.CharField(max_length=100)),
            ],
        ),
    ]
