# Generated by Django 5.0.1 on 2024-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sca',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='sca',
            name='curso',
            field=models.CharField(max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='sca',
            name='disciplinas',
            field=models.IntegerField(verbose_name='Disciplinas Matriculadas'),
        ),
        migrations.AlterField(
            model_name='sca',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sca',
            name='matricula',
            field=models.CharField(max_length=12, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='sca',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
